version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "17:00"
  open-pull-requests-limit: 10
  reviewers:
  - ardation
  assignees:
  - ardation
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.25
    - 14.14.28
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.35
    - 14.14.37
    - 14.14.41
  - dependency-name: react-markdown
    versions:
    - 5.0.3
    - 6.0.0
  - dependency-name: "@storybook/addon-viewport"
    versions:
    - 6.1.15
    - 6.1.16
    - 6.1.17
    - 6.1.18
    - 6.1.19
    - 6.1.20
    - 6.1.21
    - 6.2.1
    - 6.2.2
    - 6.2.5
    - 6.2.7
    - 6.2.8
  - dependency-name: eslint-plugin-jest
    versions:
    - 24.1.3
    - 24.1.5
    - 24.1.9
    - 24.2.0
    - 24.3.1
    - 24.3.2
    - 24.3.4
    - 24.3.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.11.10
    - 5.11.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.3
  - dependency-name: eslint-plugin-react
    versions:
    - 7.22.0
    - 7.23.1
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: lint-staged
    versions:
    - 10.5.3
